openapi: 3.0.0
info:
  title: Coupon System API
  version: 1.0.0
  description: API documentation for the Coupon System
servers:
  - url: http://localhost:8080
paths:
  /coupons/applicable:
    post:
      summary: Get applicable coupons for a cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                cart_items:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      category:
                        type: string
                order_total:
                  type: number
                timestamp:
                  type: string
      responses:
        '200':
          description: A list of applicable coupons
          content:
            application/json:
              schema:
                type: object
                properties:
                  applicable_coupons:
                    type: array
                    items:
                      type: object
                      properties:
                        coupon_code:
                          type: string
                        discount_value:
                          type: number
  /coupons/validate:
    post:
      summary: Validate a coupon for a given cart
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                coupon_code:
                  type: string
                cart_items:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                      category:
                        type: string
                order_total:
                  type: number
                timestamp:
                  type: string
      responses:
        '200':
          description: Validation result
          content:
            application/json:
              schema:
                type: object
                properties:
                  is_valid:
                    type: boolean
                  message:
                    type: string
                  discount:
                    type: object
                    properties:
                      items_discount:
                        type: number
                      charges_discount:
                        type: number
                  reason:
                    type: string